#!/usr/bin/env bash

# Repositories
EPLMP_SSH_URL=git@github.com:polarsys/eplmp.git
EPLMP_HTTPS_URL=https://github.com/polarsys/eplmp.git
DOCDOKU_PLM_SSH_URL=git@github.com:docdoku/docdoku-plm.git
DOCDOKU_PLM_HTTPS_URL=https://github.com/docdoku/docdoku-plm.git
DOCDOKU_WEB_FRONT_SSH_URL=git@github.com:docdoku/docdoku-web-front.git
DOCDOKU_WEB_FRONT_HTTPS_URL=https://github.com/docdoku/docdoku-web-front.git
DOCDOKU_PLM_SAMPLE_SSH_URL=git@github.com:docdoku/docdoku-plm-sample-data.git
DOCDOKU_PLM_SAMPLE_HTTPS_URL=https://github.com/docdoku/docdoku-plm-sample-data.git
DOCDOKU_PLM_VERSION=${DOCDOKU_PLM_VERSION:-2.5.6}
SOURCES_DIR=/src

git clone --single-branch -b ${DOCDOKU_PLM_VERSION} --depth 1 "${EPLMP_HTTPS_URL}" "${SOURCES_DIR}/eplmp"
git clone --single-branch -b ${DOCDOKU_PLM_VERSION} --depth 1 "${DOCDOKU_PLM_HTTPS_URL}" "${SOURCES_DIR}/docdoku-plm"
git clone --single-branch -b ${DOCDOKU_PLM_VERSION} --depth 1 "${DOCDOKU_WEB_FRONT_HTTPS_URL}" "${SOURCES_DIR}/docdoku-web-front"
#git clone --single-branch -b ${DOCDOKU_PLM_VERSION} --depth 1 "${DOCDOKU_PLM_SAMPLE_HTTPS_URL}" "${SOURCES_DIR}/docdoku-plm-sample-data"