version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - web-front:/usr/share/nginx/dist
    networks:
      - front
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: plm_vhost
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: YOURDOMAIN.com.crt
        target: /etc/nginx/certs/YOURDOMAIN.com.crt
      - source: YOURDOMAIN.com.key
        target: /etc/nginx/certs/YOURDOMAIN.com.key
      - source: dhparam.pem
        target: /etc/nginx/dhparam/dhparam.pem

  mariadb:
    image: mariadb:10
    volumes:
      - docdoku_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/docdokuplmsql_root_password
      - MYSQL_DATABASE=docdokuplm
      - MYSQL_USER=docdokuplm
      - MYSQL_PASSWORD_FILE=/run/secrets/docdokuplmsql_password
    secrets:
      - docdokuplmsql_root_password
      - docdokuplmsql_password
    networks:
      - db
#    ports:
#      - "13306:3306"

  back:
    image: docdoku-plm-docker_back
    depends_on:
    - mariadb
    - es
    args:
      - DOCDOKU_PLM_CODEBASE=https://docdokuplm.local:10080
      - HEAP_SIZE=1g
      - AS_ADMIN_PASSWORD=changeit
      - JWT_ENABLED=true
      - JWT_KEY=MyVerySecretPhrase
      - SESSION_ENABLED=false
      - BASIC_AUTH_ENABLED=false
      - DATABASE_USER=docdokuplm_user
      - DATABASE_PWD=changeit
      - DATABASE_URL=jdbc:mysql://db:3306/docdokuplm?useSSL=false
      - ES_SERVER_URI=http://es:9200
      - ES_SERVER_SHARDS=4
      - ES_SERVER_AUTO_EXPAND_REPLICAS=0-3
      - ES_SERVER_REPLICAS=0
      - ES_SERVER_USERNAME=elastic
      - ES_SERVER_PWD=changeme
      - SMTP_HOST=smtp
      - SMTP_PORT=1025
      - SMTP_USER=user
      - SMTP_FROM_ADDR=notifications@docdokuplm.local
      #- ES_SERVER_AWS_SERVICE=
      #- ES_SERVER_AWS_REGION=
      #- ES_SERVER_AWS_KEY=
      #- ES_SERVER_AWS_SECRET=
    volumes:
    - autodeploy:/opt/payara41/glassfish/domains/domain1/autodeploy
    - vault:/var/lib/docdoku/vault
    - plugins:/opt/plugins
    - native-libs:/opt/native-libs
    networks:
    - front
    - db
    - es
    - back
    secrets:
      - 
#    ports:
#      - "18080:8080"
#      - "14848:4848"
#      - "19009:9009"
#      - "18686:8686"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      - cluster.name=docdokuplm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
#    ports:
#      - "19200:9200"
#      - "19300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - es

  build-env:
    image: docdoku-plm-docker_build-env
    volumes:
      - src:/src
      - m2:/root/.m2
      - npm:/root/.npm
    networks:
      - back

volumes:
  docdoku_db:
  autodeploy:
  vault:
  plugins:
  native-libs:
  elasticsearch-data:
  web-front:
  src:
  m2:
  npm:

secrets:
  docdokuplmsql_root_password:
    external: true
  docdokuplmsql_password:
    external: true
  YOURDOMAIN.com.crt:
    external: true
  YOURDOMAIN.com.key:
    external: true
  dhparam.pem:
    external: true

networks:
  front:
  back:
  es:
  db:

configs:
  plm_vhost:
    external: true
