version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - web-front:/usr/share/nginx/dist
    networks:
      - front
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: plm_vhost
        target: /etc/nginx/conf.d/default.conf
      - source: webapp.properties
        target: /webapp.properties.json
    secrets:
      - source: YOURDOMAIN.com.crt
        target: /etc/nginx/certs/YOURDOMAIN.com.crt
      - source: YOURDOMAIN.com.key
        target: /etc/nginx/certs/YOURDOMAIN.com.key
      - source: dhparam.pem
        target: /etc/nginx/dhparam/dhparam.pem

  mysql:
    image: mysql:8.0.18
    volumes:
      - docdoku_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/docdokuplmsql_root_password
      - MYSQL_DATABASE=docdokuplm
      - MYSQL_USER=docdokuplm
      - MYSQL_PASSWORD_FILE=/run/secrets/docdokuplmsql_password
    secrets:
      - docdokuplmsql_root_password
      - docdokuplmsql_password
    networks:
      - db
#    ports:
#      - "13306:3306"

  docdokuplm:
    image: docdokuplm:latest
    depends_on:
      - mariadb
      - es
    environment:
      - DOCDOKU_PLM_CODEBASE=https://plm.YOURDOMAIN.com
      - HEAP_SIZE=1g
      - AS_ADMIN_PASSWORD=DOCKER-SECRET->AS_ADMIN_PASSWORD
      - JWT_ENABLED=true
      - JWT_KEY=DOCKER-SECRET->JWT_KEY
      - SESSION_ENABLED=false
      - BASIC_AUTH_ENABLED=false
      - DATABASE_USER=docdokuplm
      - DATABASE_PWD=DOCKER-SECRET->docdokuplmsql_password
      - DATABASE_URL=jdbc:mysql:http//mysql:3306/docdokuplm?useSSL=false&allowPublicKeyRetrieval=true
      - ES_SERVER_PWD=DOCKER-SECRET->ES_SERVER_PWD
      - ES_SERVER_USERNAME=elastic
      - ES_SERVER_URI=http://es:9200
      - ES_SERVER_SHARDS=4
      - ES_SERVER_AUTO_EXPAND_REPLICAS=0-3
      - ES_SERVER_REPLICAS=0
      #- ES_SERVER_AWS_SERVICE
      #- ES_SERVER_AWS_REGION
      #- ES_SERVER_AWS_KEY
      #- ES_SERVER_AWS_SECRET
      #- SMTP_HOST=localhost
      #- SMTP_PORT=25
      #- SMTP_USER=myuser
      #- SMTP_FROM_ADDR=notifications@docdokuplm.local
      #- KEYSTORE_LOCATION=/opt/payara41/keystore/dplm.jceks
      - KEYSTORE_KEY_ALIAS=mykey
      - KEYSTORE_PASS=DOCKER-SECRET->KEYSTORE_PASS
      - KEYSTORE_KEY_PASS=DOCKER-SECRET->KEYSTORE_KEY_PASS
      #- KEYSTORE_TYPE JCEKS
      #- SOLIDWORKS_LICENSE_PATH /opt/plugins/solidworks/license.txt
      #- SOLIDWORKS_SCHEMA_PATH /opt/plugins/solidworks/schema
      #- CATIA_LICENSE_PATH /opt/plugins/catia/license.txt
      #- OFFICE_PORT 8100
      #- OFFICE_HOME /usr/lib/libreoffice
      #- ASADMIN_PATH /opt/bin
      #- DOMAIN_DIR /opt/glassfish/domains/domain1
      #- VAULT_PATH /var/lib/docdoku/vault
      #- NATIVE_LIBS /opt/native-libs
    volumes:
      - autodeploy:/opt/payara41/glassfish/domains/domain1/autodeploy
      - keystore:/opt/payara41/keystore
      - vault:/var/lib/docdoku/vault
      - plugins:/opt/plugins
      - native-libs:/opt/native-libs
    networks:
      - front
      - db
      - es
      - back
    secrets:
      - AS_ADMIN_PASSWORD
      - JWT_KEY
      - docdokuplmsql_password
      - ES_SERVER_PWD
      - KEYSTORE_PASS
      - KEYSTORE_KEY_PASS
#    ports:
#      - "8080"
#      - "4848"
#      - "8009"
#      - "8181"

  es:
    image: elasticsearch:6.6.1
    environment:
      - cluster.name=docdokuplm
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    ports:
#      - "9200"
#      - "9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - es

  build:
    image: docdokuplm-build:latest
    environment:
      - DOCDOKU_PLM_VERSION=2.5.6
    volumes:
      - web-front:/volumes/web-front
      - autodeploy:/volumes/autodeploy
      - src:/src
      - m2:/root/.m2
      - npm:/root/.npm
    networks:
      - back
    deploy:
      restart_policy:
        condition: none
#    command: "init && build && deploy"

volumes:
  docdoku_db:
  autodeploy:
  keystore:
  vault:
  plugins:
  native-libs:
  elasticsearch-data:
  web-front:
  src:
  m2:
  npm:

secrets:
  docdokuplmsql_root_password:
    external: true
  docdokuplmsql_password:
    external: true
  YOURDOMAIN.com.crt:
    external: true
  YOURDOMAIN.com.key:
    external: true
  dhparam.pem:
    external: true
  AS_ADMIN_PASSWORD:
    external: true
  JWT_KEY:
    external: true
  ES_SERVER_PWD:
    external: true
  KEYSTORE_PASS:
    external: true
  KEYSTORE_KEY_PASS:
    external: true

networks:
  front:
  back:
  es:
  db:

configs:
  plm_vhost:
    external: true
  webapp.properties:
    external: true