# DocDoku, Professional Open Source
# Copyright 2006 - 2017 DocDoku SARL
#
# This file is part of DocDokuPLM.
#
# DocDokuPLM is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DocDokuPLM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DocDokuPLM.  If not, see <http://www.gnu.org/licenses/>.
#
# DocDokuPLM platform docker file

version: '2'

services:

  # Web front: nginx server on host source files  
  # volumes: static files from web front source on the host.
  front:
    build:
      context: ./front
    networks:
      - network
    ports:
      - "13000:3000"
    volumes:
      - ./volumes/web-front:/usr/share/nginx/html
  # Payara instance - JEE application server
  # Settings:
  #  - DOCDOKU_PLM_CODEBASE : Web front address
  back:
    depends_on:
      - db
      - es
    build:
      context: ./back
      args:       
        - DOCDOKU_PLM_CODEBASE=http://localhost:10080
    volumes:
      - "./volumes/autodeploy:/opt/payara41/glassfish/domains/domain1/autodeploy"
      - "./volumes/vault:/var/lib/docdoku/vault"
      - "./volumes/plugins:/opt/plugins"
      - "./volumes/native-libs:/opt/native-libs"
    networks:
      - network
    ports:
      - "18080:8080"
      - "14848:4848"
      - "19009:9009"
      - "18686:8686"  
    links:
      - "db:db"
      - "es:es"

  # Nginx global proxy
  # The application will run at http://localhost:10080, change if needed
  proxy:
    depends_on:
      - front
      - back
    build:
      context: ./proxy
    networks:
      - network
    ports:
      - "10080:10080"
      - "10081:10081"
    links:
      - "front:front"
      - "back:back"

  # ElasticSearch instance
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.10
    environment:
      - cluster.name=docdokuplm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g   
    networks:
      - network
    ports:      
      - "19200:9200"
      - "19300:9300"
    volumes:
      - ./volumes/elasticsearch-data:/usr/share/elasticsearch/data

  # MySQL instance
  db:  
    build: ./db
    volumes:
      - "./volumes/db:/var/lib/mysql"
    networks:
      - network
    ports:
      - "13306:3306"

  # DocDokuPLM build env
  build-env:
    build: ./build-env
    volumes:
      - ./volumes/src:/src
      - ./volumes/m2:/root/.m2
      - ./volumes/npm:/root/.npm

networks:
  network:
    driver: bridge

